### ISSUE TITLE
Improvements for the e2e tests of the onboarding page

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-web#262] opened 2018-06-06 14:00 UTC
- A test should be added to make sure that the create new wallet button is not activated if the seeds do not match.
- `createWallet` and `createExistingWallet` repeat the same code to fill out the form. The code should be in a separate function, to avoid repeating it. This also happens with `loadWallet` and `loadExistingWallet`.
- After `should hide accepted safeguard` a test should be added to verify that the created wallet has the correct address.
- The buttons for creating seeds with 12 and 24 words must be tested.
- A test should be added to load a wallet and check if the loaded wallet has the correct address.
- A test should be added to make sure that the disclaimer modal window can not be closed by pressing the X button or by clicking on the dark background behind the modal window.
- A test should be added to make sure that the safeguard modal window can be closed by pressing the X button and by clicking on the dark background behind the modal window.

**Comment by alexandermushinskiy** [comment] 2018-06-08 07:43
The issue is implemented.
The test "to make sure that the disclaimer modal window can not be closed by pressing the X" is not added due to disclaimer modal window doesn't have X button (it's not visible).

Also the test "load a wallet and check if the loaded wallet has the correct address." is also not added. If we add this test we should reset loaded wallet and run some steps from the previous tests (close disclaimer, fill in forms, etc.) to continue the rest tests. Do you think we should add it anyway?

**Closed** 2018-06-08 20:54 UTC
Labels: tests
