### ISSUE TITLE
Add big disclaimer warning, persistent on every page

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-web#59] opened 2018-04-22 02:02 UTC
Add a persistent warning banner that says "IF YOU USE THIS WALLET YOU MAY LOSE COINS. TESTING PURPOSES ONLY."

Use a feature flag to enable/disable this.

**Comment by alexandermushinskiy** [comment] 2018-05-03 16:31
@gz-c, the issue is implemented and merged, so it can be closed.

**Comment by gz-c** [comment] 2018-05-04 04:04
@alexandermushinskiy can you link the issue?

**Comment by alexandermushinskiy** [comment] 2018-05-04 08:09
@gz-c, I meant the current issue - "Add big disclaimer warning, persistent on every page"

**Comment by AndreiIarovoi** [comment] 2018-05-04 09:56
https://github.com/skycoin/skycoin-web/pull/80

**Closed** 2018-05-04 11:17 UTC
